version: "3.8"
services:
  backend:
    image: "pierrebonnet78/backend:1"
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - efrei

  frontend:
    image: "pierrebonnet78/frontend:1"
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - efrei
    ports:
      - "8081:80"
    depends_on:
      - backend

networks:
  efrei:
    name: efrei_network
    driver: bridge
